# Versão corrigida do arquivo de configuração para o Render.
services:
  # 1. Define o serviço para o banco de dados PostgreSQL.
  # CORREÇÃO: Usamos 'type: postgres', que é o tipo específico para bancos de dados PostgreSQL.
  - type: postgres
    name: semac-postgres-db
    plan: free # O plano gratuito é ótimo para começar.

  # 2. Define o serviço para a sua aplicação backend Spring Boot.
  - type: web
    name: semac-backend-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      # Configurações do Banco de Dados.
      # CORREÇÃO: Atualizamos o 'type' em fromService para 'postgres' para corresponder ao serviço acima.
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: postgres # Alterado de pserv para postgres
          name: semac-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: postgres # Alterado de pserv para postgres
          name: semac-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: postgres # Alterado de pserv para postgres
          name: semac-postgres-db
          property: password

      # Configuração do Hibernate.
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

      # Configurações de E-mail.
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        value: ryan.c.aguiiarr@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ciisuociovnxeoet

