# Versão corrigida do arquivo de configuração para o Render.
# CORREÇÃO FINAL: Bancos de dados e serviços são definidos em seções separadas.
databases:
  # 1. Define o banco de dados PostgreSQL.
  - name: semac-postgres-db
    plan: free # O plano gratuito é ótimo para começar.

services:
  # 2. Define o serviço para a sua aplicação backend Spring Boot.
  - type: web
    name: semac-backend-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      # Configurações do Banco de Dados.
      # CORREÇÃO: Usamos 'fromDatabase' para referenciar o banco de dados.
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: semac-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: semac-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: semac-postgres-db
          property: password

      # Configuração do Hibernate.
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

      # Configurações de E-mail.
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        value: ryan.c.aguiiarr@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ciisuociovnxeoet

