# Versão do Docker Compose.
version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL.
  db:
    image: postgres:16 # Recomendo usar uma versão específica do Postgres.
    container_name: semac_postgres_db
    environment:
      POSTGRES_DB: SEMAC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cucamole@123
    ports:
      # Mapeia a porta 5432 do contêiner para a porta 5432 da sua máquina.
      - "5432:5432"
    volumes:
      # Cria um volume para persistir os dados do banco de dados.
      - postgres_data:/var/lib/postgresql/data

  # Serviço da sua aplicação Spring Boot.
  app:
    build: . # Constrói a imagem a partir do Dockerfile no diretório atual.
    container_name: semac_backend_app
    ports:
      # Mapeia a porta 8080 do contêiner para a porta 8080 da sua máquina.
      - "8080:8080"
    environment:
      # Sobrescreve a URL do banco de dados para apontar para o serviço 'db'.
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SEMAC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Cucamole@123
      # As configurações de e-mail permanecem as mesmas.
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ryan.c.aguiiarr@gmail.com
      SPRING_MAIL_PASSWORD: ciisuociovnxeoet
    depends_on:
      # Garante que o serviço 'db' seja iniciado antes do serviço 'app'.
      - db

# Define o volume nomeado para a persistência dos dados do PostgreSQL.
volumes:
  postgres_data:
